import Navigation from "@/components/Navigation";

export default function Home() {
    return (
        <main className="h-screen flex flex-col items-center">
            <div className="w-full">
                <Navigation />
                <div>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                    <p>hello world</p>
                </div>
            </div>
        </main>
    );
}
